cabal-version: 3.0
name:          openapi3-th
version:       0
data-files:    examples/**/*.yaml

common base
  ghc-options:        -fconstraint-solver-iterations=5
  default-language:   GHC2021
  default-extensions:
    AllowAmbiguousTypes
    ApplicativeDo
    BlockArguments
    DataKinds
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    LambdaCase
    NoFieldSelectors
    NoImplicitPrelude
    OverloadedLabels
    OverloadedLists
    OverloadedRecordDot
    OverloadedStrings
    PartialTypeSignatures
    QuasiQuotes
    StrictData
    TemplateHaskell
    TypeFamilies
    UndecidableInstances
    UnicodeSyntax

library
  import:          base
  build-depends:
    , aeson
    , base
    , base64
    , bytestring
    , conduit
    , containers
    , filepath
    , generic-arbitrary
    , hspec
    , http-client
    , http-conduit
    , http-types
    , list-transformer
    , megaparsec
    , monad-validate
    , mtl
    , optics
    , quaalude
    , QuickCheck
    , template-haskell
    , text
    , transformers
    , vector
    , wai
    , warp
    , word8
    , yaml
    , yield

  hs-source-dirs:  library

  -- cabal-fmt: expand library
  exposed-modules:
    OpenApiTH
    OpenApiTH.Declare.Declare
    OpenApiTH.Declare.Options
    OpenApiTH.Grammar
    OpenApiTH.OpenApi
    OpenApiTH.OpenApi.DataType
    OpenApiTH.OpenApi.ReadSpecFile
    OpenApiTH.OpenApi.Schema
    OpenApiTH.Operation.HttpClient
    OpenApiTH.Operation.IncomingRequest
    OpenApiTH.Operation.IncomingResponse
    OpenApiTH.Operation.Message
    OpenApiTH.Operation.Operation
    OpenApiTH.Operation.OutgoingRequest
    OpenApiTH.Operation.OutgoingResponse
    OpenApiTH.Operation.Testing
    OpenApiTH.Operation.Wai
    OpenApiTH.Relation
    OpenApiTH.Web
    OpenApiTH.Web.BasicAuthentication
    OpenApiTH.Web.JsonPointer
    OpenApiTH.Web.JsonReference
    OpenApiTH.Web.ResourceLocation
    OpenApiTH.Web.Rfc2234
    OpenApiTH.Web.Rfc3986

test-suite test
  import:         base
  type:           exitcode-stdio-1.0
  main-is:        Main.hs
  hs-source-dirs: test examples properties
  build-depends:
    , base
    , bytestring
    , containers
    , hspec
    , http-conduit
    , list-transformer
    , openapi3-th
    , optics
    , quaalude
    , QuickCheck
    , template-haskell
    , text
    , warp

  -- cabal-fmt: expand examples
  other-modules:
    OpenApiGuide.BasicStructure.Main
    OpenApiGuide.MediaTypes.Main
    OpenApiGuide.ServerUrlFormat

  -- cabal-fmt: expand properties
  other-modules:  Properties.ResourceLocation.Monoid
