# https://swagger.io/docs/specification/v3_0/media-types/
paths:
  /employees:
    get:
      summary: Returns a list of employees.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    fullTime:
                      type: boolean
                  example:
                    id: 1
                    name: Jessica Right
                    fullTime: true
